# Generated by Django 3.2.9 on 2022-08-16 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=32, unique=True, verbose_name='班级编号')),
                ('name', models.CharField(default='软工01', max_length=64, unique=True, verbose_name='班级名称')),
                ('depart', models.CharField(default='计算机学院', max_length=64, verbose_name='学院')),
                ('major', models.CharField(default='软件工程', max_length=64, verbose_name='专业名称')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='课程名称')),
                ('lesson_id', models.CharField(max_length=32, unique=True, verbose_name='课程编号')),
                ('year', models.CharField(max_length=64, verbose_name='学年')),
                ('term', models.SmallIntegerField(choices=[(1, '(1)'), (2, '(2)')], verbose_name='学期')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.class', verbose_name='授课班级')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='教师姓名')),
                ('teacher_id', models.CharField(max_length=32, unique=True, verbose_name='教师编号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('student_id', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('gain_credit', models.IntegerField(verbose_name='已修学分')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.class', verbose_name='班级编号')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='课程名称')),
                ('lesson_id', models.CharField(max_length=32, unique=True, verbose_name='课程编号')),
                ('year', models.CharField(max_length=64, verbose_name='学年')),
                ('term', models.SmallIntegerField(choices=[(1, '(1)'), (2, '(2)')], verbose_name='学期')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('capacity', models.IntegerField(verbose_name='容量')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='教师编号')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='成绩')),
                ('year', models.CharField(max_length=64, verbose_name='学年')),
                ('term', models.SmallIntegerField(choices=[(1, '(1)'), (2, '(2)')], verbose_name='学期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.course', verbose_name='课程编号')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.student', verbose_name='学号')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='任课老师id')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='教师编号'),
        ),
    ]
