# Generated by Django 3.2.9 on 2022-08-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cls',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(max_length=32, verbose_name='班级编号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_id',
            field=models.CharField(max_length=32, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='lesson_id',
            field=models.CharField(max_length=32, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=32, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=32, verbose_name='教师编号'),
        ),
    ]
