# Generated by Django 3.2.9 on 2022-08-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220816_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='班级编号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='lesson_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='教师编号'),
        ),
    ]
