# Generated by Django 3.2.9 on 2022-08-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20220816_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.class', verbose_name='授课班级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='教师编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.course', verbose_name='课程编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.student', verbose_name='学号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='任课老师id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='教师编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.class', verbose_name='班级编号'),
            preserve_default=False,
        ),
    ]
