# Generated by Django 3.2.9 on 2022-08-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20220816_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='apply_sum',
            field=models.IntegerField(default=0, verbose_name='已报名人数'),
        ),
        migrations.AddField(
            model_name='selection',
            name='is_verified',
            field=models.CharField(default='否', max_length=8, verbose_name='是否确认'),
        ),
    ]
