# Generated by Django 3.2.9 on 2022-08-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20220826_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSelceted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.selection', verbose_name='课程编号')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.student', verbose_name='学号')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='教师编号')),
            ],
        ),
    ]
